modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="dalekapi"
version="1.0.0"
displayName="DalekAPI"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Samantha, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dalekapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dalekapi]]
    modId="teabs_doctor_who_mod"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dalekapi]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration